### ISSUE TITLE
Featured job card titles cut off on < 480px viewports

### ISSUE THREAD

**Issue by mdtusz** [Jobeir/jobeir#166]
Awesome work Dennis this looks awesome!

Right below 480px width, the featured job cards get their titles and location cut off though. 

<img width="481" alt="screen shot 2017-11-27 at 12 12 23 pm" src="https://user-images.githubusercontent.com/6494463/33279454-95d03900-d36c-11e7-9681-e0d3b9d47099.png">

**Comment by brotzky** [comment]
Thanks! A lot of fun and work went into this side project.

@mdtusz nice catch 👍 . That whole area is super finicky because of the absolute positioning. I'll look into fixing it tonight and get back to you with some clean screenshots.

ps: missing Montreal

**Comment by brotzky** [comment]
@mdtusz fixed in latest deploy ✌️ 

<img width="528" alt="screen shot 2017-11-28 at 7 19 26 am" src="https://user-images.githubusercontent.com/8007686/33327506-8187d48a-d40c-11e7-9e49-9a8a5fd54184.png">
